services:
  pecatu-services:
    build:
      context: .
      dockerfile: Dockerfile
    image: gitea.bengkelfajarjaya.com/gcc/pecatu-fe/stable:1.0.0
    ports:
      - "6100:80"
    restart: unless-stopped
